dist: trusty
sudo: true
install: true
branches:
  only:
  - master
script:
  - eval $(cat .env | sed 's/^/export /') && eval 'echo "$SWIFT_VERSION"'
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/swift .
  - docker tag $DOCKER_USERNAME/swift $DOCKER_USERNAME/swift:$SWIFT_VERSION
  - docker push $DOCKER_USERNAME/swift
  - cd node
  - docker build --build-arg "SWIFT_VERSION=$SWIFT_VERSION" -t $DOCKER_USERNAME/swift:node . 
  - docker push $DOCKER_USERNAME/swift