dist: trusty
sudo: true
install: true
branches:
  only:
  - swift-5.1-branch
script:
  - eval $(cat .env | sed 's/^/export /') && eval 'echo "$SWIFT_VERSION"'
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/swift .
  - docker tag $DOCKER_USERNAME/swift $DOCKER_USERNAME/swift:$SWIFT_VERSION
  - docker push $DOCKER_USERNAME/swift
